'use strict';
/**
 * B10-57806 — upload the test cases to BrowserStack Test Management (REST API v2).
 *
 * Usage:  node upload_browserstack.js --dry        # print what would be created, call nothing
 *         node upload_browserstack.js              # create, then verify
 *         node upload_browserstack.js --verify     # verify only
 *
 * Traps this implementation deliberately avoids (docs/ai/browserstack-process.md §10.6):
 *   1. `steps` is silently dropped -> the payload key must be `test_case_steps`.
 *   2. The create path is plural `/folders/{id}/test-cases`; `/folder/{id}/...` 404s.
 *   3. The project is addressed by its `PR-x` identifier, not the numeric id from the folder URL.
 *   4. Create and list paths are ASYMMETRIC — a GET on the create path 404s and reads like "folder empty".
 *      The read-back uses `GET /projects/{PR-x}/test-cases?folder_id={id}` and fails loudly on zero.
 */
const https = require('https');
const { cases } = require('./testcases.js');
const creds = require('d:/breadfast-qa/automation/config/credentials.js');

const HOST = 'test-management.browserstack.com';
const PROJECT_NUM = '2407303';
const FOLDER_ID = '53445037';
const JIRA = 'B10-57806';
const USER = creds.browserstack.tmUsername();
const TOKEN = creds.browserstack.tmApiToken();
const AUTH = 'Basic ' + Buffer.from(`${USER}:${TOKEN}`).toString('base64');
const DRY = process.argv.includes('--dry');
const VERIFY_ONLY = process.argv.includes('--verify');

function req(method, path, body) {
  return new Promise((resolve) => {
    const payload = body ? JSON.stringify(body) : null;
    const r = https.request({
      hostname: HOST, path: '/api/v2' + path, method,
      headers: {
        Authorization: AUTH, Accept: 'application/json', 'Content-Type': 'application/json',
        ...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {}),
      },
    }, (x) => { let b = ''; x.on('data', (c) => b += c); x.on('end', () => resolve({ status: x.statusCode, body: b })); });
    r.on('error', (e) => resolve({ status: 0, body: 'ERR ' + e.message }));
    if (payload) r.write(payload);
    r.end();
  });
}
const html = (s) => `<p>${String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p><br/>`;

async function resolveProject() {
  for (let p = 1; p <= 5; p++) {
    const r = await req('GET', `/projects?p=${p}`);
    if (r.status !== 200) throw new Error(`GET /projects?p=${p} -> ${r.status} ${r.body.slice(0, 160)}`);
    const list = JSON.parse(r.body).projects || [];
    if (!list.length) break;
    const hit = list.find((x) => ((x.urls && x.urls.self) || '').includes(PROJECT_NUM) || String(x.id) === PROJECT_NUM);
    if (hit) return hit.identifier;
  }
  throw new Error('could not resolve project ' + PROJECT_NUM + ' to a PR-x identifier');
}

function payloadFor(c) {
  const platform = c.platform ? ` Platform: ${c.platform}.` : '';
  return {
    test_case: {
      name: c.name,
      description:
        `Story ${JIRA} — ID Expiry Warning at BCard Sign-Up. HLS ${(c.hls || []).join(', ')}.` +
        `${(c.acs || []).length ? ` Covers ${c.acs.join(', ')}.` : ''}${platform}` +
        ` Test data case "${c.dataCase}" is computed from the DEVICE clock at run time (see automation/expiry-dates.js) —` +
        ` no expiry date is hard-coded, so the case is valid on any calendar day.` +
        `${c.note ? ` NOTE: ${c.note}` : ''}`,
      preconditions: html(
        'A test account exists with a consumed BCard invitation code that has NOT yet applied for a card ' +
        '(generated by InvitationCodeConsumedUsersGenerationTests). A Luhn-valid National ID that no previous ' +
        'application has used is available. The card-service environment is reachable.'),
      case_type: 'Functional',
      priority: c.priority,
      status: 'Active',
      template: 'test_case_steps',
      automation_status: 'not_automated',
      tags: ['ai-created', 'B10-57806', 'bcard', 'id-expiry'],
      issues: [JIRA],
      test_case_steps: c.steps.map((s) => ({ step: html(s.step), result: html(s.result) })),
    },
  };
}

(async () => {
  console.log(`project ${PROJECT_NUM} -> resolving identifier...`);
  const PR = await resolveProject();
  const f = await req('GET', `/projects/${PR}/folders/${FOLDER_ID}`);
  const folder = JSON.parse(f.body).folder || {};
  console.log(`  ${PR}  folder ${FOLDER_ID} "${folder.name}"  cases before = ${folder.cases_count}`);

  if (!VERIFY_ONLY) {
    if (DRY) {
      console.log(`\n[DRY RUN] would POST ${cases.length} cases to /projects/${PR}/folders/${FOLDER_ID}/test-cases`);
      const s = payloadFor(cases[0]);
      console.log('sample payload keys: ' + JSON.stringify(Object.keys(s.test_case)));
      console.log('  name           : ' + s.test_case.name);
      console.log('  steps key      : test_case_steps (NOT "steps")  count=' + s.test_case.test_case_steps.length);
      console.log('  first step     : ' + s.test_case.test_case_steps[0].step.slice(0, 90));
      console.log('  first result   : ' + s.test_case.test_case_steps[0].result.slice(0, 90));
      cases.forEach((c) => console.log(`   - ${c.id} ${c.priority.padEnd(8)} ${c.steps.length} steps  ${c.name}`));
      return;
    }
    let created = 0;
    for (const c of cases) {
      const r = await req('POST', `/projects/${PR}/folders/${FOLDER_ID}/test-cases`, payloadFor(c));
      if (r.status === 200 || r.status === 201) {
        const id = (JSON.parse(r.body).test_case || {}).identifier;
        console.log(`  + ${c.id} -> ${id}  (${c.steps.length} steps)`);
        created++;
      } else {
        console.log(`  ! ${c.id} FAILED ${r.status}: ${r.body.slice(0, 200)}`);
      }
    }
    console.log(`created ${created}/${cases.length}`);
  }

  // --- verify: list via the ASYMMETRIC read path and assert steps actually persisted ---
  console.log('\n=== VERIFY ===');
  const v = await req('GET', `/projects/${PR}/test-cases?folder_id=${FOLDER_ID}`);
  if (v.status !== 200) { console.log(`list failed ${v.status}: ${v.body.slice(0, 200)}`); process.exit(1); }
  const listed = JSON.parse(v.body).test_cases || [];
  console.log(`listed ${listed.length} cases in folder ${FOLDER_ID}`);
  if (!listed.length) { console.log('!! FAIL: zero cases listed — the upload did not land'); process.exit(1); }
  // The API is asymmetric on READ too: it accepts `name`/`test_case_steps` but returns `title`/`steps`.
  const expected = new Set(cases.map((c) => c.name));
  const map = {};
  let stepless = 0;
  for (const tc of listed) {
    const title = tc.title || tc.name;
    const n = (tc.steps || tc.test_case_steps || []).length;
    if (!n) stepless++;
    expected.delete(title);
    const src = cases.find((c) => c.name === title);
    if (src) map[src.id] = { tms: tc.identifier, title, steps: n, priority: tc.priority };
  }
  require('fs').writeFileSync(__dirname + '/browserstack-tms-map.json', JSON.stringify(map, null, 2));
  console.log('wrote browserstack-tms-map.json (' + Object.keys(map).length + ' entries) for @TmsLink binding');
  const after = JSON.parse((await req('GET', `/projects/${PR}/folders/${FOLDER_ID}`)).body).folder || {};
  console.log(`folder cases_count = ${after.cases_count}`);
  console.log(`cases with ZERO steps = ${stepless}  ${stepless ? '<-- the `steps` vs `test_case_steps` trap' : '(good)'}`);
  console.log(`expected names missing = ${expected.size}${expected.size ? ' -> ' + [...expected].slice(0, 5).join(' | ') : ' (all present)'}`);
  if (stepless || expected.size) process.exit(1);
  console.log('VERIFIED: all cases present with steps.');
})().catch((e) => { console.error('FATAL ' + e.message); process.exit(1); });
