/**
 * AI Explainability model — Roadmap Phase 2, Milestone 2.
 *
 * Answers the questions a reviewer asks of any AI-generated artifact: WHY it was
 * generated, WHICH acceptance criteria / comments / Figma frames / business
 * rules contributed, and under WHICH prompt/workflow/knowledge/framework
 * versions. Pure and deterministic — assembled from persisted run data, so the
 * same seam serves the report, the web explain panel, Story Replay, and
 * Analytics without a new AI call.
 *
 * Designed to extend to Visual Testing Intelligence (M3): a visual finding is
 * just another explainable artifact whose `reason` is specific ("button label
 * uses sentence case instead of title case") and whose contributions include the
 * Figma frame it was compared against.
 */
import type { Citation } from './schemas.js';
import { resolveCitations, type CitationContext, type ResolvedCitation } from './citations.js';

export type ExplainArtifactKind =
  | 'requirements_analysis'
  | 'impact_analysis'
  | 'hls_scenario'
  | 'test_case'
  | 'defect'
  | 'visual_finding' // M3
  | 'recommendation'; // M5

export interface ExplainVersions {
  prompt?: string | null;
  workflow?: string | null;
  knowledge?: string | null;
  framework?: string | null;
  platform?: string | null;
}

/** Resolved citations grouped by the reviewer question they answer. */
export interface GroupedContributions {
  acceptanceCriteria: ResolvedCitation[];
  storyComments: ResolvedCitation[];
  figmaFrames: ResolvedCitation[];
  businessRules: ResolvedCitation[];
  testCases: ResolvedCitation[];
  other: ResolvedCitation[];
}

export interface ArtifactExplanation {
  artifactKind: ExplainArtifactKind;
  artifactLabel: string; // e.g. the test-case title, the defect title
  node: string; // lifecycle node that produced it
  reason: string; // WHY it was generated — a human sentence
  contributed: GroupedContributions;
  versions: ExplainVersions;
  evidence: string[]; // file paths / links backing it
}

export interface ExplainInput {
  artifactKind: ExplainArtifactKind;
  artifactLabel: string;
  node: string;
  sources?: Citation[];
  versions?: ExplainVersions;
  evidence?: string[];
  /** Explicit reason (M3 visual findings supply a precise one); else derived. */
  reason?: string;
  citationContext?: CitationContext;
}

/** Default "why generated" sentence per artifact kind (used when no explicit reason). */
const DEFAULT_REASON: Record<ExplainArtifactKind, string> = {
  requirements_analysis:
    'Generated by STEP 1 Requirements Analysis from the story description, acceptance criteria, and comments.',
  impact_analysis:
    'Generated by STEP 4 Impact Analysis to identify impacted, regression, smoke, and automation areas.',
  hls_scenario: 'Generated by STEP 5 to cover the cited acceptance criteria / requirements as a high-level scenario.',
  test_case: 'Generated by STEP 6 test-case design to validate the cited acceptance criteria and cover the HLS.',
  defect: 'Recorded during execution because a step’s actual result violated the cited acceptance criterion, design, or rule.',
  visual_finding: 'Detected during visual comparison of the captured screen against the Figma design.',
  recommendation: 'Proposed after the run to improve future test quality, coverage, or automation.',
};

function group(resolved: ResolvedCitation[]): GroupedContributions {
  const g: GroupedContributions = {
    acceptanceCriteria: [],
    storyComments: [],
    figmaFrames: [],
    businessRules: [],
    testCases: [],
    other: [],
  };
  for (const c of resolved) {
    if (c.kind === 'ac') g.acceptanceCriteria.push(c);
    else if (c.kind === 'comment') g.storyComments.push(c);
    else if (c.kind === 'figma') g.figmaFrames.push(c);
    else if (c.kind === 'rule') g.businessRules.push(c);
    else if (c.kind === 'testcase') g.testCases.push(c);
    else g.other.push(c); // story, requirement, …
  }
  return g;
}

/** Build a structured explanation for one artifact. Pure. */
export function explainArtifact(input: ExplainInput): ArtifactExplanation {
  const resolved = resolveCitations(input.sources, input.citationContext ?? {});
  return {
    artifactKind: input.artifactKind,
    artifactLabel: input.artifactLabel,
    node: input.node,
    reason: input.reason?.trim() || DEFAULT_REASON[input.artifactKind],
    contributed: group(resolved),
    versions: input.versions ?? {},
    evidence: input.evidence ?? [],
  };
}
